site_name: DAQ Software Suite
site_url: https://dune-timing.github.io/ 
edit_uri: ""
repo_url: https://github.com/sparamesvarab/Dune-timing-documentation
repo_name: DUNE-DAQ
theme:
  name: material

# nav:
    # - Home: 'Home.md'
    # ll- About: 'about.md'